version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kondate-planner"
s3_prefix = "kondate-planner"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []

[default.build]
[default.build.parameters]
parallel = true
